import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Provider from "./_provider";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body className={rubik.className}>
					<Provider>
						<ThemeProvider attribute='class' defaultTheme='light' disableTransitionOnChange>
							{children}
						</ThemeProvider>
					</Provider>
				</body>
			</html>
		</ClerkProvider>
	);
}
